# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79adfd3dc2d6e0a9de368cd0966142b5a84f7b97075d3537754c26a827006a18fec587689970fe5f503e1ce30a9a4732826615d807dd8ad07dea875a4c1f67d2

test:
  secret_key_base: 523953be17824fd95aa77d53e85d4a1a873ffcaf26c60d997342439aee3d36d9436473948303c43f0e44fdb5b3f1097652780f166ac85cb6cdf17144a89f9adb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
